require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'fitnessvwork' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'RNImageToPdf', :path => '../node_modules/react-native-image-to-pdf'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #   'RCTLinkingIOS',
  # ]


  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'

  pod 'RNAppleHealthKit', :path => '../node_modules/react-native-health'

  target 'fitnessvworkTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
    end
  end
end
